In [5]:
import numpy as np
from sklearn import model_selection, datasets

C:\ProgramData\Anaconda3\lib\importlib\_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


In [6]:
iris = datasets.load_iris()

Основная функция разбиения выборок model_selection.train_test_split

In [7]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, 
                                                                                     test_size = 0.3)

## Создание отложенных фолдов для валидации

In [9]:
#сгенерируем короткое подобие датасета, где элементы совпадают с порядковым номером
X = range(0,10)

KFold -- Обычное разбиение выборки на n_splits наборов, где $\frac{1}{\text{n_splits}}$ часть выборки -- тестовая

In [22]:
kf = model_selection.KFold(n_splits = 5, shuffle=True)
for train_indices, test_indices in kf.split(X):
    print(train_indices, test_indices)

[1 2 3 4 5 7 8 9] [0 6]
[0 2 3 4 5 6 7 9] [1 8]
[0 1 3 4 5 6 7 8] [2 9]
[0 1 2 3 5 6 8 9] [4 7]
[0 1 2 4 6 7 8 9] [3 5]


StratifiedKFold -- Разбиение аналогичное KFold но только с сохранением отношений классов в обучающей и тестовой выборках

In [24]:
y = np.array([0] * 5 + [1] * 5)
print(y)

skf = model_selection.StratifiedKFold(n_splits = 2, shuffle = True)
for train_indices, test_indices in skf.split(X, y):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[2 3 5 8] [0 1 4 6 7 9]
[0 1 4 6 7 9] [2 3 5 8]


ShuffleSplit -- В отличии от KFold не вводится ограничений на повторение элементов от выборки к выборке ( то есть каждая выборка генерируется независимоот предыдущей)

In [26]:
target = np.array([0] * 5 + [1] * 5)
print(target)

sss = model_selection.StratifiedShuffleSplit(n_splits = 4, test_size = 0.2)
for train_indices, test_indices in sss.split(X, target):
    print(train_indices, test_indices)

[0 0 0 0 0 1 1 1 1 1]
[6 7 4 3 8 0 1 5] [9 2]
[0 7 6 8 1 3 5 4] [9 2]
[1 8 9 4 5 2 0 6] [7 3]
[9 5 1 0 2 8 7 4] [3 6]


Leave-One-Out -- Выделяет в тестовую выборку по 1 объекту (получаем количество выборок = количеству объектов)

In [27]:
loo = model_selection.LeaveOneOut()

for train_indices, test_index in loo.split(X):
    print(train_indices, test_index)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]
